services:
  neo4j:
    image: neo4j:5.15-community
    environment:
      # Basic authentication
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      
      # Network settings
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      
      # Database settings
      - NEO4J_initial_dbms_default__database=authdata
      
      # Memory settings (increased for better performance)
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_dbms_memory_transaction_total_max=4G
      
      # APOC Plugin configuration
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      
      # Additional performance settings
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_server_jvm_additional=-XX:+UseG1GC
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    networks:
      - app-network
   

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      neo4j:
        condition: service_started
      ollama:
        condition: service_started
    ports:
      - "7860:7860"
    volumes:
      - ./src:/app/src
      - neo4j_import:/import
    networks:
      - app-network


volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  ollama_data:
networks:
  app-network:
    driver: bridge